module: SwiftUIWavyRectangleShape
author: CypherPoet
author_url: https://github.com/CypherPoet
copyright: Copyright 2021 CypherPoet
github_url: https://github.com/CypherPoet/SwiftUIWavyRectangleShape
theme: fullwidth
swift_build_tool: spm
clean: true
output: ./docs
min_acl: internal
